### ISSUE TITLE
Error when generating pdb file

### ISSUE THREAD

**Issue by Joey-Xue** [gjoni/trRosetta#10]
I want to test the performance of trRosetta on a bunch of proteins I have, I got the .npz files from predict.py but when I tried to use trRosetta to output the predicted structure I got following error:
PyRosetta-4 2020 [Rosetta PyRosetta4.Release.python36.ubuntu 2020.50+release.1295438cd4bd2be39c9dbbfab8db669ab62415ab 2020-12-12T00:30:01] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
temp folder:      /dev/shm/64q8sw5m
dist restraints:  8485
omega restraints: 8437
theta restraints: 17282
phi restraints:   17292
mutation: G26A
mutation: G73A
mutation: G81A
mutation: G89A
mutation: G95A
mutation: G117A
mutation: G150A
mutation: G151A

ERROR: Pose::set_phi( Size const seqpos , Real const setting ): residue seqpos is not part of a protein, peptoid, or carbohydrate!
ERROR:: Exit from: /home/benchmark/rosetta/source/src/core/pose/Pose.cc line: 1069
Traceback (most recent call last):
  File "/home/zyxue/Record/trRosetta/trRosetta.py", line 212, in <module>
    main()
  File "/home/zyxue/Record/trRosetta/trRosetta.py", line 110, in main
    set_random_dihedral(pose)
  File "/home/zyxue/Record/trRosetta/utils_ros.py", line 152, in set_random_dihedral
    pose.set_phi(i,phi)
RuntimeError:

File: /home/benchmark/rosetta/source/src/core/pose/Pose.cc:1069
[ ERROR ] UtilityExitException
ERROR: Pose::set_phi( Size const seqpos , Real const setting ): residue seqpos is not part of a protein, peptoid, or carbohydrate!

It seems like there's some residues that are not protein but that's impossible since the sequence I used was directly generated from pdb structure and the sequence alignment and first step prediction of constraints went well, I wonder what does this error mean and if there's a way to fix it.

**Comment by gjoni** [comment]
Could you share a sequence or an msa for the protein which produces those errors so that I can have a closer look?

**Comment by Joey-Xue** [comment]
Hi gioni,
Thanks for your reply, here I attached the fasta, a3m file I used for prediction and the predicted npz file. Thanks for your help!
[Erroreg.zip](https://github.com/gjoni/trRosetta/files/6292908/Erroreg.zip)

**Comment by gjoni** [comment]
There are 'X' letters at positions 123-130 in the 2aaoA.fasta file which is  the likely cause of the errors. The folding script can only work with the 20 standard amino acid types.

**Comment by Joey-Xue** [comment]
Thanks for your help! I checked my sequences and they do have "X" in the fasta which I thought doesn't matter previously. Another problem I have is that, I'm trying to make predictions for hundreds of sequences, so I generated .npz file for all of them first and then used trRosetta to make .pdb  structure file for them in parallel by multiprocessing module. However, when the runing went on it filled the innodes and space of my computer's temporary folder /dev/shm, I think it's because trRosetta create a temporary folder there containing a lot of temporary files that used up the space and didn't delete them in time. Do you have any idea on freeing up the space after one trRosetta process is finished? Alternatively, I can also add a line in my code to delete the temporary folder after the process ends but the name of the temporary folder is random so I can't get access to it automatically. 

Many thanks for your help!

**Comment by Joey-Xue** [comment]
This is the error message I got:

Traceback (most recent call last):
  File "/home/zyxue/Record/trRosetta/trRosetta.py", line 212, in <module>
    main()
  File "/home/zyxue/Record/trRosetta/utils_ros.py", line 112, in gen_rst
    f.close()
OSError: [Errno 28] No space left on device

And this is the result I got from running df -i
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
udev            4102733     600  4102133    1% /dev
tmpfs           4108486    1060  4107426    1% /run
/dev/nvme0n1p2 61022208 1833243 59188965    4% /
tmpfs           4108486 3859057   249429   94% /dev/shm

The /dev/shm folder is completely filled by the temporary folders.

**Comment by gjoni** [comment]
Yes, by default the script writes many intermediate files in /dev/shm. You can manually change it to whatever location you want by modifying 'WDIR' field in trRosetta/data/params.json. The intermediate files are automatically deleted if the script finishes successfully. It is possible that if you run many jobs in parallel /dev/shm gets exhausted quickly and the running jobs crash without cleaning the folder. I would suggest either increasing the default size of /dev/shm or changing it in params.json to some other location which has more free space.
