### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by Gradie** [gjoni/trRosetta#11]
Hi, If you use GPU to accelerate predict process, what is the acceleration effect?
I used Tesla T4, tensorflow-1,14-gpu，tested the consumption time of sess.run() in predict.py. The acceleration effect is only 1.5 times that of the CPU. Is this normal? How many times the acceleration should be achieved? Looking forward to your reply, thanks.

**Comment by gjoni** [comment]
Hi,
I'm not exactly sure what your benchmarking setup is, but you may need to run sess.run() multiple times to see the difference between cpu and gpu. During the first execution of sess.run() considerable amount of time is spent on setting up the computation   graph on both cpu and gpu but subsequent runs should be much faster. Locally we get 50-100 fold decrease in running time when a gpu is used.

-Ivan

**Comment by Gradie** [comment]
Thanks for your reply. I just used this repository(gjoni/trRosetta) and download pre-trained network(model2019_07.tar.bz2), and python ./network/predict.py -m ./model2019_07 example/T1001.a3m example/T1001.npz to run this program. Then tested the consumption time of sess.run() in predict.py. I ran sess.run() with 100 loops, and the time spent on cpu is 643s, on gpu is 430s. Confused.

**Comment by Gradie** [comment]
I use tf timeline module to record time. Looks normal. I get 14 fold decrease in running time when Tesla T4 is used. Thanks again.

**Comment by gjoni** [comment]
Good! Depending on what you trying to do, you may also want to try moving the evaluation loop inside the sess.run() call as it is done in trRosetta/network/predict_many.py (end of the script) so that multiple inputs are processed in a single sess.run() call which is way more efficient than calling it multiple times.

**Comment by Gradie** [comment]
python ./network/predict_many.py -m ./model2019_07 example example  Is this order?

**Comment by gjoni** [comment]
Yes, this is correct. Currently there is only one .a3m file in the example folder, so there will be no difference from running predict.py. To see the difference, you may want to run predict_many.py on folder which stores many .a3m files.

**Comment by Gradie** [comment]
Hi,Ivan.When I run predict.py with CPU and GPU, I get the result as shown in the image below.
CPU:


GPU:
The acceleration effect is about 3 times.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ivan ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 中午11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gjoni/trRosetta] GPU acceleration (#11)





 
Yes, this is correct. Currently there is only one .a3m file in the example folder, so there will be no difference from running predict.py. To see the difference, you may want to run predict_many.py on folder which stores many .a3m files.
