### ISSUE TITLE
Details on computational profile of the pipeline

### ISSUE THREAD

**Issue by bkj** [gjoni/trRosetta#2]
Hi --

I'm interested in understanding the computational profile of these kinds of structure prediction tasks.

As I understand it, there are three broad steps to go from input to 3d structure:
    a) "feature engineering" via MSAs, etc to form LxLx526 input tensor
    b) forward pass through the CNN to predict distances/angles
    c) structure determination to realize an actual 3d structure

Are you able to comment on the relative cost in terms of wall-clock time / compute required / etc of those three steps?  Is one step substantially more costly than the others? Do you have a sense of how long it would take to go from raw input -> 3d structure for a single example?

(I'm primarily concerned w/ inference-time costs here -- I see in your paper that training the CNN takes ~ 9 days on a single GPU.)

Thanks!

**Comment by gjoni** [comment]
Hi Ben,
I guess you recently sent me an email which I just replied to. Closing the issue.
Thanks!
