### ISSUE TITLE
Glycine Residues

### ISSUE THREAD

**Issue by HanneWhitt** [gjoni/trRosetta#3]
Thank you for providing this excellent resource!

Can I ask a question about a minor detail: how did you define d, omega, theta and phi when one or both of the residues in a pair is a glycine? What is the network predicting in these cases? 

I could not find this in your paper or supplementary info - sorry if I have missed it!

Many thanks!

**Comment by sokrypton** [comment]
Hi Hanne,
In the case of glycine, we just pretend it is an alanine.
Given the length between CA-CB, angle between N-CA-CB and dihedral between C-N-CA-CB is fixed, you can always compute the location of a "virtual" CB given the location of C,N and CA.

So the prediction is between these "virtual" CB atoms.

During modeling (in rosetta), we pretend G are A during the initial stages, then mutate the A back to G for later refinement stage.

**Comment by HanneWhitt** [comment]
Thank you for your response. Can I ask, would it be possible to see the formula (or code) that you used to calculate the position of this virtual CB? 

I want to ensure my approach is consistent with yours.
