### ISSUE TITLE
Question about the distance histogram

### ISSUE THREAD

**Issue by AndersJing** [gjoni/trRosetta#4]
Hi Ivan,

Thanks for sharing the source code, it's a great job.

For the distance histogram prediction, as the paper says: "The distance range (2 to 20 Å) is binned into 36 equally spaced segments, 0.5 Å each, plus one bin indicating that residues are not in contact." So the output shape of the network is L*L*37, and the last bin corresponds to the >20 Å distance.

But when converting the distance distribution to energy potential, what the article says is "For the distance distribution, the probability value for the last bin, i.e., [19.5, 20], is used as a reference state ... ", which is contradictory to the definition of the last bin (>20 Å but not [19.5, 20]).

Is it my misunderstanding or is there something wrong?

**Comment by gjoni** [comment]
Hi Anders,

Your question is quite relevant - we haven't described bin numbering carefully enough in the paper. The >20A distance bin is actually bin #0 in the code, and the last bin corresponds to distances 19.5..20A - and this is the bin participating in the reference state correction.

Ivan

**Comment by AndersJing** [comment]
That makes sense.

Thanks for the clarification.
