### ISSUE TITLE
Question about trRosetta running

### ISSUE THREAD

**Issue by kch38896** [gjoni/trRosetta#7]
Hi there.

I want generate structure models from trRosetta. So, I typed below.
   python trRosetta/trRosetta.py trRosetta/example/T1008.npz trRosetta/example/T1008.fasta model.pdb

But, the output is it

temp folder:      /dev/shm/3rsb8fq5
dist restraints:  2877
omega restraints: 2872
theta restraints: 5835
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trRosetta/trRosetta.py", line 212, in <module>
    main()
  File "trRosetta/trRosetta.py", line 58, in main
    rst = gen_rst(npz,tmpdir,params)
  File "/tf/trRosetta/utils_ros.py", line 137, in gen_rst
    f.close()
OSError: [Errno 28] No space left on device

my shm folder has inode=7.9M,  IUse%=1%, size=64M
How can I fix it?

**Comment by gjoni** [comment]
Hi,

I believe you are referring to the structure prediction module which is not part of this repo. That one is using /dev/shm by default to store various temporary data. To change the default location you can specify any other folder by changing "WDIR" field in trRosetta/data/params.json.

Ivan
